FROM python:3.9

COPY ./data /app/data/
COPY ./requirements.txt /app/
COPY ./generate_data.py /app/
COPY ./generate_users.py /app/

WORKDIR /app

RUN pip install -r requirements.txt

CMD ["tail", "-f", "/dev/null"]
